export default {
  BACK: "BACK",
  MECHANICS: "MECHANICS",
  NEW_CHARACTER: "NEW_CHARACTER",
  SAS: "SAS",
  PROFESSIONS: "PROFESSIONS",
  LANGUAGES: "LANGUAGES",
  MAGIC: "MAGIC",
  NEW_NPC: "NEW_NPC",
};
