export default {
  BACK: "BACK",
  CODEX_READ: "CODEX_READ",
  CODEX_FRAGMENT: "CODEX_FRAGMENT",
  CODEX_CREATE_FRAGMENT: "CODEX_CREATE_FRAGMENT",
  CODEX_FRAGMENT_READ: "CODEX_FRAGMENT_READ",
  CODEX_CREATE_CATEGORY: "CODEX_CREATE_CATEGORY",
  CODEX_CATEGORY_READ: "CODEX_CATEGORY_READ",
  CODEX_CATEGORY: "CODEX_CATEGORY",
};
